apiVersion: v1
kind: ConfigMap
metadata:
  name: scale-cassandra
  namespace: cnsbench-library
  annotations:
    role: scale-scripts
data:
  scale.sh: |
    #!/bin/bash

    kubectl patch -nrook-cassandra clusters.cassandra.rook.io/$1 --type=json -p '[{"op": "replace", "path": "/spec/datacenter/racks/0/members", "value": '${2}'}]'
