apiVersion: v1
kind: ConfigMap
metadata:
  name: megahit
  namespace: library
  labels:
    type: workload
  annotations:
    cnsbench.default.pvcsize: 7Gi
data:
  pvc.yaml: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: vol-{{ACTION_NAME}}-{{INSTANCE_NUM}}
      namespace: default
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{pvcsize}}
      storageClassName: {{storageClass}}
      volumeMode: Filesystem
  workload.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: megahit-{{ACTION_NAME}}-{{INSTANCE_NUM}}
      namespace: default
      annotations:
        sync: "1"
        role: workload
        outputFile: /output/output
        parser: null-parser
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: alexmerenstein/workloads/megahit
            imagePullPolicy: IfNotPresent
            name: megahit
            command: ["sh", "-c", "mkdir -p /output; cp cut* /data/; megahit -1 /data/cut1* -2 /data/cut2* -m .5 -t 1 -o /data/out > /output/"]
            volumeMounts:
              - mountPath: /data/
                name: data
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: vol-{{ACTION_NAME}}-{{INSTANCE_NUM}}
