apiVersion: v1
kind: ConfigMap
metadata:
  name: null-parser
  namespace: library
  labels:
    type: parser
  annotations:
    container: dwdraju/alpine-curl-jq
data:
  null.sh: "#!/bin/sh\n\ncat $1\nexit 0\n"
