apiVersion: v1
kind: ConfigMap
metadata:
  name: ycsb
  namespace: cnsbench-library
  labels:
    type: workload
  annotations:
    cnsbench.default.dblayer: basic
    cnsbench.default.workload: workloada
    cnsbench.default.recordcount: "50000"
    cnsbench.default.operationcount: "50000"
    cnsbench.default.otherparams: ""
data:
  workload.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: ycsb-mongo-{{ACTION_NAME}}-{{INSTANCE_NUM}}
      namespace: default
      annotations:
        sync: "1"
        role: workload
        outputFole: /output/output
        parser: null-parser
        duplicate: "true"
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: {{ACTION_NAME}}-client
        spec:
          restartPolicy: Never
          initContainers:
          - name: init-ycsb
            image: cnsbench/ycsb
            workingDir: /ycsb-0.17.0
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c", "count=$(( {{recordcount}}/$NUM_INSTANCES )); start=$(( $INSTANCE_NUM*$count )); ./bin/ycsb.sh load {{dblayer}} -s -P workloads/{{workload}} {{otherparams}} -p recordcount={{recordcount}} -p insertstart=$start -p insertcount=$count"]
          containers:
          - name: ycsb
            image: cnsbench/ycsb
            workingDir: /ycsb-0.17.0
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c", "./bin/ycsb.sh run {{dblayer}} -s -P workloads/{{workload}} {{otherparams}} -p recordcount={{recordcount}} -p operationcount={{operationcount}} | tee /output/output"]
