apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-name
  namespace: cnsbench-library
  labels:
    type: workload
  annotations:
    cnsbench.default.param-one: param-one-default
    cnsbench.default.param-two: param-two-default
data:
  config.yaml: |
    kind: ConfigMap
    metadata:
      name: workload-config
      namespace: default
      ...
  pvc.yaml: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: vol-{{ACTION_NAME}}-{{INSTANCE_NUM}}
      namespace: default
    spec:
      ...
  workload.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: workload-{{ACTION_NAME}}-{{INSTANCE_NUM}}
      namespace: default
      annotations:
        role: workload
        outputFile: /output/output
        parser: null-parser
    spec:
      ...
